\set ON_ERROR_STOP on
begin;
create function pg_temp.assert(ok boolean, label text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end $$;
do $$
declare
 u1 uuid := gen_random_uuid(); u2 uuid := gen_random_uuid(); u3 uuid := gen_random_uuid();
 b1 uuid := gen_random_uuid(); b2 uuid := gen_random_uuid(); k1 uuid := gen_random_uuid(); k2 uuid := gen_random_uuid();
 event1 uuid := gen_random_uuid(); device1 uuid; device2 uuid; claimed record; other record; n integer;
begin
 insert into auth.users(id) values(u1),(u2),(u3);
 insert into public.businesses values(b1,now()),(b2,now());
 insert into public.business_members(business_id,user_id) values(b1,u1),(b1,u2),(b2,u2),(b2,u3);
 insert into public.bookings(id,business_id,scheduled_for,status) values(k1,b1,now()+interval '1 day','CONFIRMED'),(k2,b2,now()-interval '1 minute','IN_PROGRESS');
 perform set_config('request.jwt.claim.sub',u1::text,true);
 set local role authenticated;
 device1 := public.register_push_subscription('https://fcm.googleapis.com/test-one',repeat('a',87),repeat('b',22));
 perform pg_temp.assert(device1 = public.register_push_subscription('https://fcm.googleapis.com/test-one',repeat('a',87),repeat('b',22)), 'idempotent subscription registration');
 begin perform endpoint from public.push_subscriptions; raise exception 'unexpected access'; exception when insufficient_privilege then null; end;
 begin perform public.claim_notification_push(); raise exception 'unexpected access'; exception when insufficient_privilege then null; end;
 reset role;
 perform set_config('request.jwt.claim.sub',u2::text,true);
 set local role authenticated;
 begin perform public.register_push_subscription('https://fcm.googleapis.com/test-one',repeat('a',87),repeat('b',22)); raise exception 'unexpected ownership'; exception when insufficient_privilege then null; end;
 device2 := public.register_push_subscription('https://updates.push.services.mozilla.com/test-two',repeat('a',87),repeat('b',22));
 reset role;
 insert into public.booking_confirmations values(event1,b1,k1);
 perform private.emit_booking_notification(b1,k1,'CUSTOMER_CONFIRMED',event1);
 perform pg_temp.assert((select count(*)=2 from public.notifications),'one durable event per eligible member');
 perform pg_temp.assert((select count(*)=2 from private.notification_push_deliveries),'one delivery per device, duplicate source suppressed');
 perform set_config('request.jwt.claim.sub',u3::text,true);
 set local role authenticated;
 perform pg_temp.assert((select count(*)=0 from public.notifications),'unrelated user cannot read notifications');
 reset role;
 perform set_config('request.jwt.claim.sub',u1::text,true);
 set local role authenticated;
 perform pg_temp.assert((select count(*)=1 from public.notifications),'own RLS view');
 begin insert into public.notifications(user_id,business_id,booking_id,notification_type,event_id) values(u1,b1,k1,'BOOKING_OVERDUE',k1); raise exception 'unexpected insert'; exception when insufficient_privilege then null; end;
 begin update public.notifications set notification_type='BOOKING_OVERDUE'; raise exception 'unexpected update'; exception when insufficient_privilege then null; end;
 reset role;
 select * into claimed from public.claim_notification_push(1);
 perform pg_temp.assert(claimed.delivery_id is not null,'delivery claim returns work');
 select * into other from public.claim_notification_push(1);
 perform pg_temp.assert(other.delivery_id <> claimed.delivery_id,'successive workers cannot claim same work');
 perform pg_temp.assert(not public.finish_notification_push(claimed.delivery_id,gen_random_uuid(),201),'stale or forged lease rejected');
 perform pg_temp.assert(public.finish_notification_push(claimed.delivery_id,claimed.lease_token,503,90),'explicit transient failure recorded');
 perform pg_temp.assert((select state='pending' and attempt_count=1 and next_attempt_at>=now()+interval '90 seconds' from private.notification_push_deliveries where id=claimed.delivery_id),'retry respects provider delay');
 perform public.finish_notification_push(other.delivery_id,other.lease_token,null);
 perform pg_temp.assert((select state='unknown' from private.notification_push_deliveries where id=other.delivery_id),'ambiguous provider failure is terminal');
 update private.notification_push_deliveries set next_attempt_at=now()-interval '1 second' where id=claimed.delivery_id;
 select * into claimed from public.claim_notification_push(1);
 perform public.finish_notification_push(claimed.delivery_id,claimed.lease_token,410);
 perform pg_temp.assert((select revoked_at is not null from public.push_subscriptions where id=(select subscription_id from private.notification_push_deliveries where id=claimed.delivery_id)),'410 revokes only the claimed device');
 perform pg_temp.assert(public.process_overdue_notifications()=1,'exact overdue predicate finds newly due booking');
 perform pg_temp.assert(public.process_overdue_notifications()=0,'overdue dedupe');
 delete from public.notifications where booking_id=k2;
 perform pg_temp.assert(public.process_overdue_notifications()=0,'overdue receipt survives notification retention');
 insert into public.notification_preferences(user_id,customer_feedback) values(u1,false);
 insert into public.feedback values(gen_random_uuid(),b1,k1);
 perform pg_temp.assert((select count(*)=2 from public.notifications where notification_type='CUSTOMER_FEEDBACK_RECEIVED'),'push preference does not suppress durable history');
 perform pg_temp.assert(not exists(select 1 from private.notification_push_deliveries d join public.notifications n on n.id=d.notification_id where n.user_id=u1 and n.notification_type='CUSTOMER_FEEDBACK_RECEIVED'),'disabled category has no push queue');
 insert into public.booking_amendments values(gen_random_uuid(),b1,k1,'PENDING_CUSTOMER');
 update public.booking_amendments set status='CONFIRMED';
 update public.booking_amendments set status='CONFIRMED';
 perform pg_temp.assert((select count(*)=2 from public.notifications where notification_type='AMENDMENT_RESPONDED'),'only real amendment transition emits');
 insert into public.booking_addons values(gen_random_uuid(),b1,k1,'AWAITING_CUSTOMER');
 update public.booking_addons set status='CONFIRMED';
 perform pg_temp.assert((select count(*)=2 from public.notifications where notification_type='ADD_ON_RESPONDED'),'customer addon transition emits');
 update auth.users set banned_until=now()+interval '1 day' where id=u1;
 perform set_config('request.jwt.claim.sub',u1::text,true);
 set local role authenticated;
 perform pg_temp.assert((select count(*)=0 from public.notifications),'disabled user cannot read');
 reset role;
 delete from public.business_members where business_id=b1 and user_id=u2;
 perform pg_temp.assert(not exists(select 1 from public.notifications where user_id=u2 and business_id=b1),'membership revocation immediately removes inbox and deliveries');
 insert into public.business_members(business_id,user_id) values(b1,u2);
 perform pg_temp.assert(not exists(select 1 from public.notifications where user_id=u2 and business_id=b1),'rejoining does not restore old notifications');
 perform public.maintain_notifications();
 perform pg_temp.assert(not exists(select 1 from public.notifications where user_id=u1),'maintenance purges disabled account events');
 perform pg_temp.assert(not has_table_privilege('anon','public.notifications','SELECT'),'anonymous table access denied');
 perform pg_temp.assert(not has_function_privilege('authenticated','private.emit_booking_notification(uuid,uuid,text,uuid)','EXECUTE'),'ordinary users cannot emit events');
end $$;
rollback;
