-- Execute only inside the disposable native runner with a schema-only export.
set check_function_bodies=true;
insert into auth.users(id,email) values('20000000-0000-4000-8000-000000000001','synthetic@example.com');
insert into public.profiles(id,display_name) values('20000000-0000-4000-8000-000000000001','Synthetic');
insert into public.businesses(id,name,slug,category,created_by,onboarding_completed_at) values('10000000-0000-4000-8000-000000000001','Synthetic Vendor','synthetic-vendor','Other','20000000-0000-4000-8000-000000000001',now());
insert into public.business_members(business_id,user_id,role,status) values('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','owner','active');
insert into private.whatsapp_pilot_businesses values('10000000-0000-4000-8000-000000000001',true);
do $$
declare pilot uuid:='10000000-0000-4000-8000-000000000001'; b record; r record; repeated record; a record; addon record; second_booking record; result jsonb; mode text; t1 text;t2 text;t3 text;t4 text;t5 text;
begin
  perform set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
  foreach mode in array array['both','whatsapp_only','email_only'] loop
    t1:=encode(extensions.gen_random_bytes(32),'hex'); t2:=encode(extensions.gen_random_bytes(32),'hex'); t3:=encode(extensions.gen_random_bytes(32),'hex'); t4:=encode(extensions.gen_random_bytes(32),'hex'); t5:=encode(extensions.gen_random_bytes(32),'hex');
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    select * into b from public.create_booking_with_channels(mode<>'whatsapp_only',mode<>'email_only','+15555550123',true,pilot,'new',null,'Synthetic fixture',null,null,'Synthetic booking',null,'EUR',1000,0,now()+interval '1 day',null);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    select * into r from public.create_booking_confirmation_request_with_channels(b.booking_id,'fixture@example.com',t1,now()+interval '24 hours');
    if mode='whatsapp_only' and r.email_event_id is not null then raise exception 'whatsapp_only_created_email'; end if;
    if mode='email_only' and exists(select 1 from public.whatsapp_events where booking_id=b.booking_id) then raise exception 'email_only_created_whatsapp'; end if;
    perform set_config('request.jwt.claim.sub','',true);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    result:=public.confirm_booking_by_token_hash(encode(extensions.digest(t1,'sha256'),'hex'),'fixture@example.com',null);
    perform set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
    if result->>'status'<>'confirmed' then raise exception 'confirmation_probe_failed'; end if;
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    select * into r from public.reschedule_booking_with_notification_with_channels(b.booking_id,now()+interval '2 days',t2,now()+interval '24 hours');
    perform set_config('request.jwt.claim.sub','',true);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    result:=public.confirm_booking_by_token_hash(encode(extensions.digest(t2,'sha256'),'hex'),'fixture@example.com',null);
    perform set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    select * into a from public.create_booking_amendment_with_channels(b.booking_id,'Synthetic change','Synthetic amended booking',null,'EUR',1000,0,now()+interval '2 days',t3,now()+interval '24 hours');
    perform set_config('request.jwt.claim.sub','',true);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    result:=public.confirm_booking_amendment_by_token_hash(encode(extensions.digest(t3,'sha256'),'hex'));
    perform set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    select * into addon from public.create_booking_addon(b.booking_id,'Synthetic add-on',null,100,0);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    select * into r from public.submit_booking_addon_with_channels(addon.booking_addon_id,t4,now()+interval '24 hours');
    perform set_config('request.jwt.claim.sub','',true);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    result:=public.confirm_booking_addon_by_token_hash(encode(extensions.digest(t4,'sha256'),'hex'));
    perform set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    perform public.transition_booking_status(b.booking_id,'READY',null);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    select * into r from public.deliver_booking_with_feedback(b.booking_id);
    select * into repeated from public.deliver_booking_with_feedback(b.booking_id);
    if repeated.feedback_link_id is distinct from r.feedback_link_id or repeated.feedback_token is distinct from r.feedback_token or not repeated.reused then
      raise exception 'delivery_retry_changed_capability';
    end if;
    if mode<>'email_only' then
      if (select count(distinct event_type) from public.whatsapp_events where booking_id=b.booking_id)<>8 then raise exception 'lifecycle_event_coverage_failed'; end if;
      if (select count(*) from private.whatsapp_capabilities c join public.whatsapp_events w on w.id=c.event_id where w.booking_id=b.booking_id)<>5 then raise exception 'capability_capture_failed'; end if;
      if mode='whatsapp_only' and exists(select 1 from public.email_events where booking_id=b.booking_id) then raise exception 'whatsapp_only_email_leak'; end if;
    end if;
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    select * into second_booking from public.create_booking_with_channels(mode<>'whatsapp_only',mode<>'email_only','+15555550123',true,pilot,'new',null,'Synthetic cancellation fixture',null,null,'Synthetic cancellation booking',null,'EUR',0,0,now()+interval '1 day',null);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    select * into r from public.create_booking_confirmation_request_with_channels(second_booking.booking_id,'fixture@example.com',t5,now()+interval '24 hours');
    perform set_config('request.jwt.claim.sub','',true);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    perform public.confirm_booking_by_token_hash(encode(extensions.digest(t5,'sha256'),'hex'),'fixture@example.com',null);
    perform set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
    perform set_config('app.booking_transition_allowed','false',true);
    perform set_config('app.booking_reschedule_allowed','false',true);
    perform set_config('app.booking_amendment_allowed','false',true);
    perform set_config('app.booking_addon_workflow_allowed','false',true);
    perform public.transition_booking_status(second_booking.booking_id,'CANCELLED','Synthetic cancellation');
    if mode<>'email_only' and not exists(select 1 from public.whatsapp_events where booking_id=second_booking.booking_id and event_type='BOOKING_CANCELLED') then raise exception 'cancellation_missing'; end if;
  end loop;
end $$;
select 'PASS: complete original booking lifecycle RPCs with nine events across Both, WhatsApp-only and Email-only; native disposable database, no external sends';
